### PR TITLE
Breaking change: refactor using plenary.job

### LINKED ISSUE #25: quickfix output doesn't work in windows 10
When I use output = "quickfix", I got the following error:

Error executing  lua <USERDIR>\.vim\plugged\yabs.nvim\lua\yabs\util.lua:58: bad argument #1 to 'new_pipe' (boolean expected, got no value)

I am using this config:
python = {
	tasks = {
		run = {
			command = "dtx-env\\Scripts\\python %",
			output = "quickfix",
			} 
		},
	},
on neovim 5.1 on windows 10.

My guess that this is related to windows, hence the title.

P.S. Great plugin! I am using it even without quickfix.

### PR DESCRIPTION
**Pull request by Shatur**
* Now plenary is required.
* Respect quotes in command.
* `on_exit` accepts plenary.job and exit code to control the behavior.

Fixes #25.

### CODE REVIEW

**Comment by pianocomposer321** [comment]
What exactly do you mean by "respect quotes in command"? Can you point me to the file that was changed to add this?

**Comment by pianocomposer321** [comment]
Oh, nvm, I think I see it. It's that huge regex at the end of "utils.lua", in the `split_cmd` function, right?

**Comment by pianocomposer321** [comment]
For now, I think I would prefer it if we didn't have any breaking changes in this PR (other than requiring plenary, of course). That would mean changing every occurrence of `opts.on_exit` with `function(_, _) opts.on_exit() end`. I'm not saying we can't leverage plenary's API in the future, but I don't know much about how it works so I don't think introducing it before I'm able to think about it more is a good idea.

If you can separate out the other changes, I'll approve this PR. Essentially I want this to be a pure refactor at this point, and not introduce any new functionality or breaking changes from the user's perspective, other than one additional dependency. That will just make things easier all the way around.

**Review by pianocomposer321 — CHANGES_REQUESTED** [review]
For now, I think I would prefer it if we didn't have any breaking changes in this PR (other than requiring plenary, of course). That would mean changing every occurrence of `opts.on_exit` with `function(_, _) opts.on_exit() end`. I'm not saying we can't leverage plenary's API in the future, but I don't know much about how it works so I don't think introducing it before I'm able to think about it more is a good idea.

If you can separate out the other changes, I'll approve this PR. Essentially I want this to be a pure refactor at this point, and not introduce any new functionality or breaking changes from the user's perspective, other than one additional dependency. That will just make things easier all the way around.

**Comment by Shatur** [comment]
> Oh, nvm, I think I see it. It's that huge regex at the end of "utils.lua", in the split_cmd function, right?

Yep. Libuv (`vim.loop`) use array for arguments. Previously you used `vim.split (cmd, ' ')` to split commands by space. But if a command is presented as `cat "file with spaces.txt"`, then it will be split as `cat`, `"file`, `with`, `spaces"` which is wrong. The provided `split_cmd` fixes this issue by respecting quotes (previous command will be spitted as `cat` and `file with spaces`).

> For now, I think I would prefer it if we didn't have any breaking changes in this PR (other than requiring plenary, of course). That would mean changing every occurrence of opts.on_exit with function(_, _) opts.on_exit() end. I'm not saying we can't leverage plenary's API in the future, but I don't know much about how it works so I don't think introducing it before I'm able to think about it more is a good idea.

Hm... I re-read you previous code and it looks like actually there no breaking change. You called `on_exit` on success and on failure, right? Plenary's `on_exit` just have additional arguments to re-run the job or read it's output using first argument and let user check exit code in second argument (which is a very useful feature!). But in Lua you can pass a function with less number of arguments, they will be discarded. So it's a backward-compatible change.

**Comment by pianocomposer321** [comment]
You're right, sorry about that :wink:.

It was the section in README.md that threw me. I think we could be a bit more clear there about the signature of the function. I don't think we should assume that the user will know what a plenary Job is, and it should also be clear that the function does not need to have a signature (otherwise it will look like a breaking change even though it isn't, which is what had me confused).

File: lua/yabs/outputs/buffer.lua [hunk 1]
```diff
@@ -18,28 +21,25 @@ local function make_scratch_buffer(height, position)
   return vim.fn.bufnr()
 end
 
-local function append_to_buffer(buffer, lines)
```
Comment (pianocomposer321) [inline lua/yabs/outputs/buffer.lua:21]: What's the rationale for deleting this? I know it's just one line, but I put it in a separate function on purpose because without it it's pretty unclear what `vim.api.nvim_buf_set_lines()` does in this case.

**Comment by Shatur** [comment]
> You're right, sorry about that 

No need to apologize, I myself thought it was a breaking change and mentioned it in the PR description, but then I re-read the code more carefully and it turned that the change is backward-compatible.

> I think we could be a bit more clear there about the signature of the function.

Sounds reasonable, I improve the README.

File: lua/yabs/outputs/buffer.lua (hunk 1 above)
Comment (Shatur) [reply lua/yabs/outputs/buffer.lua:21]: I like the separation, but in this case it looks a little too explicit to me:

```lua
local function append_to_buffer(line)
  vim.api.nvim_buf_set_lines(bufnr, -2, -2, false, { line })
end

local function on_read(error, data)
  append_to_buffer(error and error or data)
end
```

But how about to just change `on_read` name into `append_to_buffer`?

Comment (pianocomposer321) [reply lua/yabs/outputs/buffer.lua:21]: That sounds like a reasonable solution, particularly now that the function will just be that line instead of two.

**Comment by Shatur** [comment]
Pushed the discussed changes and updated the README.

File: README.md [hunk 2]
```diff
@@ -71,7 +71,12 @@ require('yabs'):setup({
             -- WARNING: this api is experimental and subject to
             -- changes
             require('yabs'):run_task('build', {
-              on_exit = function(Job, exit_code) -- Job here is a plenary.job object
+              -- Job here is a plenary.job object that represents
+              -- the finished task, read more about it here:
+              -- https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/job.lua
```
Comment (pianocomposer321) [inline README.md:76]: I think here we could also link to https://github.com/nvim-lua/plenary.nvim#plenaryjob.

File: README.md [hunk 3]
```diff
@@ -71,7 +71,12 @@ require('yabs'):setup({
...
+              on_exit = function(Job, exit_code)
+                -- You can omit extra arguments or skip
+                -- some of them using _ for the name
```
Comment (pianocomposer321) [inline README.md:79]: Not a huge deal but I think

```lua
-- The parameters `Job` and `exit_code` are optional
-- leaving one or both of them out will not cause an error
```

is clearer. Obviously it doesn't have to be that exact wording, but I think including the word "optional" makes it clear what you're trying to say.

**Review by pianocomposer321 — COMMENTED** [review]
Other than that, looks good!

**Comment by Shatur** [comment]
Updated the README with the suggestions :)

**Review by pianocomposer321 — APPROVED** [review]

**Comment by Shatur** [comment]
@pianocomposer321 I tested it myself, but will wait for users feedback.

**Comment by pianocomposer321** [comment]
> @pianocomposer321 I tested it myself, but will wait for users feedback.

Sounds great, I appreciate your caution!
